"""Curated content banks for ON NOW Trivia picture rounds + Puzzle Party.

Kept out of trivia.py so game logic stays readable.
"""

# (country name, iso2 code for flagcdn.com)
FLAG_BANK = [
    ("Australia", "au"), ("Japan", "jp"), ("Brazil", "br"), ("Canada", "ca"),
    ("Germany", "de"), ("France", "fr"), ("Italy", "it"), ("Spain", "es"),
    ("Portugal", "pt"), ("Greece", "gr"), ("United Kingdom", "gb"),
    ("United States", "us"), ("Mexico", "mx"), ("Argentina", "ar"),
    ("Chile", "cl"), ("China", "cn"), ("India", "in"), ("Indonesia", "id"),
    ("Thailand", "th"), ("Vietnam", "vn"), ("South Korea", "kr"),
    ("New Zealand", "nz"), ("South Africa", "za"), ("Egypt", "eg"),
    ("Kenya", "ke"), ("Nigeria", "ng"), ("Morocco", "ma"), ("Turkey", "tr"),
    ("Sweden", "se"), ("Norway", "no"), ("Denmark", "dk"), ("Finland", "fi"),
    ("Iceland", "is"), ("Ireland", "ie"), ("Netherlands", "nl"),
    ("Belgium", "be"), ("Switzerland", "ch"), ("Austria", "at"),
    ("Poland", "pl"), ("Ukraine", "ua"), ("Saudi Arabia", "sa"),
    ("United Arab Emirates", "ae"), ("Pakistan", "pk"), ("Philippines", "ph"),
    ("Malaysia", "my"), ("Singapore", "sg"), ("Fiji", "fj"), ("Jamaica", "jm"),
    ("Cuba", "cu"), ("Colombia", "co"), ("Peru", "pe"), ("Croatia", "hr"),
]

# Wikipedia page title → display answer.  Images resolved at runtime
# via the Wikipedia REST summary API (cached in-process).
ANIMAL_BANK = [
    {"title": "Giraffe", "answer": "Giraffe"},
    {"title": "Red panda", "answer": "Red panda"},
    {"title": "Snow leopard", "answer": "Snow leopard"},
    {"title": "Platypus", "answer": "Platypus"},
    {"title": "Axolotl", "answer": "Axolotl"},
    {"title": "Koala", "answer": "Koala"},
    {"title": "Common wombat", "answer": "Wombat"},
    {"title": "Short-beaked echidna", "answer": "Echidna"},
    {"title": "Okapi", "answer": "Okapi"},
    {"title": "Meerkat", "answer": "Meerkat"},
    {"title": "Capybara", "answer": "Capybara"},
    {"title": "Pangolin", "answer": "Pangolin"},
    {"title": "Chameleon", "answer": "Chameleon"},
    {"title": "Toco toucan", "answer": "Toucan"},
    {"title": "Indian peafowl", "answer": "Peacock"},
    {"title": "Greater flamingo", "answer": "Flamingo"},
    {"title": "European hedgehog", "answer": "Hedgehog"},
    {"title": "Raccoon", "answer": "Raccoon"},
    {"title": "Emperor penguin", "answer": "Penguin"},
    {"title": "Polar bear", "answer": "Polar bear"},
    {"title": "Cheetah", "answer": "Cheetah"},
    {"title": "Hippopotamus", "answer": "Hippopotamus"},
    {"title": "Komodo dragon", "answer": "Komodo dragon"},
    {"title": "Narwhal", "answer": "Narwhal"},
    {"title": "Orca", "answer": "Orca"},
    {"title": "Manatee", "answer": "Manatee"},
    {"title": "Sea otter", "answer": "Sea otter"},
    {"title": "Bald eagle", "answer": "Bald eagle"},
    {"title": "Red kangaroo", "answer": "Kangaroo"},
    {"title": "Ring-tailed lemur", "answer": "Lemur"},
    {"title": "Nine-banded armadillo", "answer": "Armadillo"},
    {"title": "Quokka", "answer": "Quokka"},
    {"title": "Highland cattle", "answer": "Highland cow"},
    {"title": "Alpaca", "answer": "Alpaca"},
    {"title": "Tasmanian devil", "answer": "Tasmanian devil"},
    {"title": "Blue-ringed octopus", "answer": "Blue-ringed octopus"},
]

LANDMARK_BANK = [
    {"title": "Eiffel Tower", "answer": "Paris, France"},
    {"title": "Taj Mahal", "answer": "Agra, India"},
    {"title": "Statue of Liberty", "answer": "New York, USA"},
    {"title": "Colosseum", "answer": "Rome, Italy"},
    {"title": "Big Ben", "answer": "London, England"},
    {"title": "Sydney Opera House", "answer": "Sydney, Australia"},
    {"title": "Golden Gate Bridge", "answer": "San Francisco, USA"},
    {"title": "Machu Picchu", "answer": "Peru"},
    {"title": "Christ the Redeemer (statue)", "answer": "Rio de Janeiro, Brazil"},
    {"title": "Great Wall of China", "answer": "China"},
    {"title": "Stonehenge", "answer": "Wiltshire, England"},
    {"title": "Mount Rushmore", "answer": "South Dakota, USA"},
    {"title": "Burj Khalifa", "answer": "Dubai, UAE"},
    {"title": "Leaning Tower of Pisa", "answer": "Pisa, Italy"},
    {"title": "Sagrada Família", "answer": "Barcelona, Spain"},
    {"title": "Angkor Wat", "answer": "Cambodia"},
    {"title": "Petra", "answer": "Jordan"},
    {"title": "Chichen Itza", "answer": "Mexico"},
    {"title": "Neuschwanstein Castle", "answer": "Bavaria, Germany"},
    {"title": "Brandenburg Gate", "answer": "Berlin, Germany"},
    {"title": "Empire State Building", "answer": "New York City, USA"},
    {"title": "CN Tower", "answer": "Toronto, Canada"},
    {"title": "Table Mountain", "answer": "Cape Town, South Africa"},
    {"title": "Uluru", "answer": "Northern Territory, Australia"},
    {"title": "Mount Fuji", "answer": "Japan"},
    {"title": "Santorini", "answer": "Greece"},
    {"title": "Hollywood Sign", "answer": "Los Angeles, USA"},
    {"title": "Tower Bridge", "answer": "London, England"},
    {"title": "Hagia Sophia", "answer": "Istanbul, Turkey"},
    {"title": "Moai", "answer": "Easter Island, Chile"},
    {"title": "Forbidden City", "answer": "Beijing, China"},
    {"title": "Red Square", "answer": "Moscow, Russia"},
    {"title": "Acropolis of Athens", "answer": "Athens, Greece"},
    {"title": "Kinkaku-ji", "answer": "Kyoto, Japan"},
    {"title": "Matterhorn", "answer": "Switzerland"},
]

# word to scramble, category hint, three same-category wrong options
ANAGRAM_BANK = [
    {"word": "LONDON", "hint": "European capital city", "wrong": ["LISBON", "DUBLIN", "MADRID"]},
    {"word": "GUITAR", "hint": "Musical instrument", "wrong": ["VIOLIN", "TRUMPET", "BANJO"]},
    {"word": "DOLPHIN", "hint": "Ocean animal", "wrong": ["OCTOPUS", "PENGUIN", "WALRUS"]},
    {"word": "PYRAMID", "hint": "Ancient structure", "wrong": ["CASTLE", "TEMPLE", "PALACE"]},
    {"word": "RAINBOW", "hint": "Seen in the sky", "wrong": ["THUNDER", "CYCLONE", "TORNADO"]},
    {"word": "CHOCOLATE", "hint": "Sweet treat", "wrong": ["CARAMEL", "LIQUORICE", "MARZIPAN"]},
    {"word": "FOOTBALL", "hint": "Sport", "wrong": ["BASEBALL", "SOFTBALL", "HANDBALL"]},
    {"word": "KANGAROO", "hint": "Australian animal", "wrong": ["WALLABY", "POSSUM", "DINGO"]},
    {"word": "TELESCOPE", "hint": "Science instrument", "wrong": ["MICROSCOPE", "BAROMETER", "COMPASS"]},
    {"word": "VOLCANO", "hint": "Natural feature", "wrong": ["GLACIER", "CANYON", "GEYSER"]},
    {"word": "BUTTERFLY", "hint": "Insect", "wrong": ["DRAGONFLY", "LADYBIRD", "CRICKET"]},
    {"word": "SPAGHETTI", "hint": "Italian food", "wrong": ["LASAGNE", "RAVIOLI", "GNOCCHI"]},
    {"word": "ELEPHANT", "hint": "Large animal", "wrong": ["GIRAFFE", "GORILLA", "BUFFALO"]},
    {"word": "COMPUTER", "hint": "Technology", "wrong": ["KEYBOARD", "MONITOR", "PRINTER"]},
    {"word": "SUNFLOWER", "hint": "Plant", "wrong": ["DAFFODIL", "LAVENDER", "MARIGOLD"]},
    {"word": "BASKETBALL", "hint": "Sport", "wrong": ["VOLLEYBALL", "BADMINTON", "ATHLETICS"]},
    {"word": "AVOCADO", "hint": "Fruit", "wrong": ["COCONUT", "APRICOT", "RHUBARB"]},
    {"word": "PENGUIN", "hint": "Bird", "wrong": ["PELICAN", "SEAGULL", "PUFFIN"]},
    {"word": "DIAMOND", "hint": "Gemstone", "wrong": ["EMERALD", "SAPPHIRE", "OPAL"]},
    {"word": "HOSPITAL", "hint": "Building", "wrong": ["LIBRARY", "STADIUM", "MUSEUM"]},
    {"word": "MOUNTAIN", "hint": "Landscape", "wrong": ["GLACIER", "DESERT", "LAGOON"]},
    {"word": "ORCHESTRA", "hint": "Music", "wrong": ["SYMPHONY", "CONCERTO", "QUARTET"]},
    {"word": "CROCODILE", "hint": "Reptile", "wrong": ["ALLIGATOR", "CHAMELEON", "IGUANA"]},
    {"word": "HELICOPTER", "hint": "Transport", "wrong": ["AEROPLANE", "SUBMARINE", "MOTORBIKE"]},
    {"word": "STRAWBERRY", "hint": "Fruit", "wrong": ["BLUEBERRY", "RASPBERRY", "CRANBERRY"]},
    {"word": "LIGHTHOUSE", "hint": "Coastal building", "wrong": ["WINDMILL", "BOATSHED", "HARBOUR"]},
    {"word": "TREASURE", "hint": "A pirate's goal", "wrong": ["DOUBLOON", "GALLEON", "COMPASS"]},
    {"word": "FIREWORKS", "hint": "Celebration", "wrong": ["CONFETTI", "BALLOONS", "STREAMERS"]},
    {"word": "UNIVERSE", "hint": "Space", "wrong": ["GALAXY", "NEBULA", "COSMOS"]},
    {"word": "SANDWICH", "hint": "Lunch food", "wrong": ["BAGUETTE", "CROISSANT", "TORTILLA"]},
]

EMOJI_BANK = [
    {"emoji": "🕷️🧑", "answer": "Spider-Man", "hint": "Superhero", "wrong": ["Batman", "Iron Man", "Superman"]},
    {"emoji": "👑🦁", "answer": "The Lion King", "hint": "Movie", "wrong": ["Madagascar", "The Jungle Book", "Zootopia"]},
    {"emoji": "🧊🛳️💔", "answer": "Titanic", "hint": "Movie", "wrong": ["Jaws", "Cast Away", "Life of Pi"]},
    {"emoji": "🦈🎵👶", "answer": "Baby Shark", "hint": "Song", "wrong": ["Old MacDonald", "Wheels on the Bus", "Hakuna Matata"]},
    {"emoji": "🌧️💜🎤", "answer": "Purple Rain", "hint": "Song", "wrong": ["Singin' in the Rain", "November Rain", "Umbrella"]},
    {"emoji": "🍕🐢🥷", "answer": "Teenage Mutant Ninja Turtles", "hint": "TV / Movie", "wrong": ["Finding Nemo", "Kung Fu Panda", "Shrek"]},
    {"emoji": "🧙‍♂️💍🌋", "answer": "The Lord of the Rings", "hint": "Movie", "wrong": ["Harry Potter", "Narnia", "Eragon"]},
    {"emoji": "⚡🤓🦉", "answer": "Harry Potter", "hint": "Movie / Book", "wrong": ["Percy Jackson", "Peter Pan", "Matilda"]},
    {"emoji": "🥶👸⛄", "answer": "Frozen", "hint": "Movie", "wrong": ["Moana", "Tangled", "Brave"]},
    {"emoji": "🐟🔍", "answer": "Finding Nemo", "hint": "Movie", "wrong": ["Shark Tale", "The Little Mermaid", "Free Willy"]},
    {"emoji": "🦖🏞️🚙", "answer": "Jurassic Park", "hint": "Movie", "wrong": ["King Kong", "Godzilla", "Ice Age"]},
    {"emoji": "🤖❤️🌱", "answer": "WALL-E", "hint": "Movie", "wrong": ["Big Hero 6", "Robots", "Transformers"]},
    {"emoji": "🎈🏠👴", "answer": "Up", "hint": "Movie", "wrong": ["Home Alone", "Monster House", "Coco"]},
    {"emoji": "🍫🏭🎫", "answer": "Charlie and the Chocolate Factory", "hint": "Movie", "wrong": ["Ratatouille", "Cloudy with a Chance of Meatballs", "The Grinch"]},
    {"emoji": "👻🚫🔫", "answer": "Ghostbusters", "hint": "Movie", "wrong": ["Casper", "Beetlejuice", "Scooby-Doo"]},
    {"emoji": "🦇🌃", "answer": "Batman", "hint": "Superhero", "wrong": ["Spider-Man", "Iron Man", "The Flash"]},
    {"emoji": "🌟⚔️🚀", "answer": "Star Wars", "hint": "Movie", "wrong": ["Star Trek", "Dune", "Avatar"]},
    {"emoji": "🕰️🚗⚡", "answer": "Back to the Future", "hint": "Movie", "wrong": ["The Time Machine", "Looper", "Tenet"]},
    {"emoji": "🐼🥋", "answer": "Kung Fu Panda", "hint": "Movie", "wrong": ["Mulan", "The Karate Kid", "Rush Hour"]},
    {"emoji": "🧜‍♀️🌊🦀", "answer": "The Little Mermaid", "hint": "Movie", "wrong": ["Moana", "Aquaman", "Splash"]},
    {"emoji": "🏝️📦🏐", "answer": "Cast Away", "hint": "Movie", "wrong": ["Life of Pi", "The Beach", "Robinson Crusoe"]},
    {"emoji": "🐝🎬", "answer": "Bee Movie", "hint": "Movie", "wrong": ["Antz", "A Bug's Life", "Maya the Bee"]},
    {"emoji": "🎩🐇🫖", "answer": "Alice in Wonderland", "hint": "Movie / Book", "wrong": ["The Wizard of Oz", "Peter Pan", "Coraline"]},
    {"emoji": "🦍🗽✈️", "answer": "King Kong", "hint": "Movie", "wrong": ["Godzilla", "Rampage", "Planet of the Apes"]},
    {"emoji": "🧟🚶🏙️", "answer": "The Walking Dead", "hint": "TV show", "wrong": ["Stranger Things", "Z Nation", "Lost"]},
    {"emoji": "👨‍🍳🐀🇫🇷", "answer": "Ratatouille", "hint": "Movie", "wrong": ["Chef", "Burnt", "The Menu"]},
    {"emoji": "🕵️🔍🇬🇧", "answer": "Sherlock Holmes", "hint": "Detective", "wrong": ["James Bond", "Hercule Poirot", "Columbo"]},
    {"emoji": "⭕🦑🎮", "answer": "Squid Game", "hint": "TV show", "wrong": ["Money Heist", "Alice in Borderland", "The Circle"]},
]

# closest-number showdown questions
NUMBER_BANK = [
    {"q": "How tall is Mount Everest in metres?", "answer": 8849, "unit": "m"},
    {"q": "How many bones are in the adult human body?", "answer": 206, "unit": "bones"},
    {"q": "In what year did the Titanic sink?", "answer": 1912, "unit": ""},
    {"q": "How many keys are on a standard piano?", "answer": 88, "unit": "keys"},
    {"q": "How long is the Great Wall of China in kilometres?", "answer": 21196, "unit": "km"},
    {"q": "How many minutes are in a full day?", "answer": 1440, "unit": "minutes"},
    {"q": "In what year did humans first land on the Moon?", "answer": 1969, "unit": ""},
    {"q": "How many countries are there in Africa?", "answer": 54, "unit": "countries"},
    {"q": "What's a cheetah's top speed in km/h?", "answer": 112, "unit": "km/h"},
    {"q": "How many steps to the top of the Eiffel Tower?", "answer": 1665, "unit": "steps"},
    {"q": "How deep is the Mariana Trench in metres?", "answer": 10935, "unit": "m"},
    {"q": "How many species of penguin exist?", "answer": 18, "unit": "species"},
    {"q": "In what year was the first iPhone released?", "answer": 2007, "unit": ""},
    {"q": "How many time zones does Russia span?", "answer": 11, "unit": "time zones"},
    {"q": "How hot is the surface of the Sun in °C?", "answer": 5500, "unit": "°C"},
    {"q": "How many hearts does an octopus have?", "answer": 3, "unit": "hearts"},
    {"q": "How many players are on the field per AFL team?", "answer": 18, "unit": "players"},
    {"q": "What's the population of Australia in millions?", "answer": 27, "unit": "million"},
    {"q": "How long is a marathon in kilometres?", "answer": 42.2, "unit": "km"},
    {"q": "In what year did World War II end?", "answer": 1945, "unit": ""},
    {"q": "How many known moons does Jupiter have?", "answer": 95, "unit": "moons"},
    {"q": "How tall is the Sydney Harbour Bridge in metres?", "answer": 134, "unit": "m"},
    {"q": "How many teeth does an adult human have?", "answer": 32, "unit": "teeth"},
    {"q": "What's the top speed of a Formula 1 car in km/h?", "answer": 372, "unit": "km/h"},
    {"q": "How many islands make up Fiji?", "answer": 333, "unit": "islands"},
    {"q": "In what year was Google founded?", "answer": 1998, "unit": ""},
    {"q": "How many litres of blood are in the human body?", "answer": 5, "unit": "L"},
    {"q": "How many storeys does the Burj Khalifa have?", "answer": 163, "unit": "storeys"},
    {"q": "How old was the oldest person ever recorded?", "answer": 122, "unit": "years"},
    {"q": "How many piano concertos did Mozart write?", "answer": 27, "unit": ""},
]
