package tv.vesper.app

import android.content.Context
import android.util.Log
import android.view.SurfaceHolder
import android.view.SurfaceView
import android.view.ViewGroup
import android.widget.FrameLayout
import `dev`.jdtech.mpv.MPVLib
import java.io.File

/**
 * v2.16.42 — MPV (libmpv) playback engine embedded inside
 * [ExoPlayerActivity].
 *
 * Renders into a SurfaceView (never TextureView) with MPV's `vo=gpu`
 * output using MediaCodec HW decode.  Frame-pacing profile is on by
 * default (interpolation + display-resample) — that's the entire
 * reason MPV was added to the app.
 *
 * Provides the same engine-agnostic API surface as [VesperVlcEngine]:
 * setMedia, play/pause/seek, position/duration, track pickers,
 * release.  Events forwarded to a [Listener] on the main thread.
 */
class VesperMpvEngine(
    private val ctx: Context,
    parent: ViewGroup,
    private val listener: Listener,
    interpolation: Boolean = true,
) {
    interface Listener {
        fun onMpvPlaying()
        fun onMpvPaused()
        fun onMpvBuffering(buffering: Boolean)
        fun onMpvEnded()
        fun onMpvError()
        fun onMpvContentFps(fps: Float) {}
    }

    companion object {
        private const val TAG = "VesperMpvEngine"
        @Volatile private var libLoaded = false

        /** Load libmpv/libplayer .so files once per process. */
        private fun ensureLibsLoaded() {
            if (libLoaded) return
            synchronized(this) {
                if (libLoaded) return
                System.loadLibrary("mpv")
                System.loadLibrary("player")
                libLoaded = true
            }
        }
    }

    private val handler = android.os.Handler(android.os.Looper.getMainLooper())
    val surfaceView: SurfaceView
    private var initialised = false
    private var released = false
    private var pendingUrl: String? = null
    private var pendingStartAtMs = 0L
    private var pendingSubUrl = ""
    private var fpsFired = false

    init {
        ensureLibsLoaded()
        seedConfigDir()
        MPVLib.create(ctx.applicationContext)
        applyBaseOptions(interpolation)
        MPVLib.init()
        initialised = true
        MPVLib.addObserver(mpvObserver)
        // Property observers — MPV_FORMAT_* constants from client.h.
        // Using raw ints defensively; jdtech vs aniyomi vs is.xyz
        // forks all name the inner class slightly differently, but
        // the wire format values are stable across libmpv releases.
        try {
            MPVLib.observeProperty("time-pos",          MPVLib.MPV_FORMAT_DOUBLE)
            MPVLib.observeProperty("duration",          MPVLib.MPV_FORMAT_DOUBLE)
            MPVLib.observeProperty("pause",             MPVLib.MPV_FORMAT_FLAG)
            MPVLib.observeProperty("paused-for-cache",  MPVLib.MPV_FORMAT_FLAG)
            MPVLib.observeProperty("eof-reached",       MPVLib.MPV_FORMAT_FLAG)
            MPVLib.observeProperty("estimated-vf-fps",  MPVLib.MPV_FORMAT_DOUBLE)
        } catch (t: Throwable) {
            Log.w(TAG, "observeProperty failed", t)
        }
        surfaceView = SurfaceView(ctx).apply {
            layoutParams = FrameLayout.LayoutParams(
                FrameLayout.LayoutParams.MATCH_PARENT,
                FrameLayout.LayoutParams.MATCH_PARENT,
            )
            setBackgroundColor(0xFF000000.toInt())
            isFocusable = false
            isFocusableInTouchMode = false
            holder.addCallback(surfaceCallback)
        }
        parent.addView(surfaceView)
    }

    /** Seed a minimal mpv.conf in the app's filesDir; libmpv reads
     *  it during init and honours the frame-pacing options.  Written
     *  once — subsequent launches just re-use the file. */
    private fun seedConfigDir() {
        try {
            val dir = File(ctx.filesDir, "mpv")
            if (!dir.exists()) dir.mkdirs()
            val conf = File(dir, "mpv.conf")
            if (!conf.exists()) {
                conf.writeText(
                    """
                    # Auto-generated by Vesper v2.16.42 — do not edit.
                    # Frame-pacing profile for smooth slow pans.
                    vo=gpu
                    hwdec=mediacodec-copy
                    profile=fast
                    interpolation=yes
                    video-sync=display-resample
                    tscale=oversample
                    # Never drop a frame on VOD — every frame must land
                    # on its scheduled vsync.
                    framedrop=no
                    # Aggressive read-ahead for HTTP CDN streams.
                    cache=yes
                    cache-secs=30
                    demuxer-max-bytes=150MiB
                    demuxer-readahead-secs=20
                    # English audio/sub preferred (matches VLC engine).
                    alang=eng,en
                    slang=eng,en
                    # Match Android's audio hardware.
                    audio-channels=auto-safe
                    """.trimIndent()
                )
            }
        } catch (t: Throwable) {
            Log.w(TAG, "seedConfigDir failed", t)
        }
    }

    /** Options that MUST be set BEFORE `init()` — vo, hwdec, config. */
    private fun applyBaseOptions(interpolation: Boolean) {
        try {
            val cfgDir = File(ctx.filesDir, "mpv").path
            MPVLib.setOptionString("config-dir", cfgDir)
            MPVLib.setOptionString("config", "yes")
            MPVLib.setOptionString("vo", "gpu")
            MPVLib.setOptionString("hwdec", "mediacodec-copy")
            MPVLib.setOptionString("keep-open", "always")
            // Frame-pacing block — can be flipped off via ctor arg.
            MPVLib.setOptionString("interpolation", if (interpolation) "yes" else "no")
            MPVLib.setOptionString("video-sync",
                if (interpolation) "display-resample" else "audio")
            MPVLib.setOptionString("tscale", "oversample")
            MPVLib.setOptionString("framedrop", "no")
        } catch (t: Throwable) {
            Log.w(TAG, "applyBaseOptions failed", t)
        }
    }

    private val surfaceCallback = object : SurfaceHolder.Callback {
        override fun surfaceCreated(holder: SurfaceHolder) {
            try {
                MPVLib.attachSurface(holder.surface)
                MPVLib.setPropertyString("vid", "auto")
                val url = pendingUrl
                if (url != null) {
                    loadInternal(url, pendingStartAtMs, pendingSubUrl)
                    pendingUrl = null
                }
            } catch (t: Throwable) {
                Log.w(TAG, "attachSurface failed", t)
                listener.onMpvError()
            }
        }

        override fun surfaceChanged(
            holder: SurfaceHolder, format: Int, width: Int, height: Int,
        ) { /* no-op — MPV auto-detects size */ }

        override fun surfaceDestroyed(holder: SurfaceHolder) {
            try {
                MPVLib.setPropertyString("vid", "no")
                MPVLib.detachSurface()
            } catch (t: Throwable) {
                Log.w(TAG, "detachSurface failed", t)
            }
        }
    }

    private val mpvObserver = object : MPVLib.EventObserver {
        override fun eventProperty(property: String) { /* strings only */ }
        override fun eventProperty(property: String, value: Long) { /* ints */ }
        override fun eventProperty(property: String, value: Boolean) {
            handler.post {
                when (property) {
                    "pause" -> {
                        if (value) listener.onMpvPaused() else listener.onMpvPlaying()
                    }
                    "paused-for-cache" -> listener.onMpvBuffering(value)
                    "eof-reached" -> if (value) listener.onMpvEnded()
                }
            }
        }
        override fun eventProperty(property: String, value: String) { /* strings */ }
        override fun eventProperty(property: String, value: Double) {
            if (property == "estimated-vf-fps" && !fpsFired && value > 0.5) {
                fpsFired = true
                handler.post { listener.onMpvContentFps(value.toFloat()) }
            }
        }
        override fun event(eventId: Int) {
            when (eventId) {
                MPVLib.MPV_EVENT_PLAYBACK_RESTART -> handler.post {
                    listener.onMpvBuffering(false)
                    listener.onMpvPlaying()
                }
                MPVLib.MPV_EVENT_END_FILE -> { /* eof-reached distinguishes */ }
                MPVLib.MPV_EVENT_SHUTDOWN -> { /* release path */ }
            }
        }
    }

    /** Load + start a stream.  Reuses the same MPV core so stream
     *  swaps never re-init the JNI stack. */
    fun setMedia(url: String, startAtMs: Long, subUrl: String = "", live: Boolean = false) {
        fpsFired = false
        // Live profile: shrink caches for fast zapping.
        try {
            if (live) {
                MPVLib.setPropertyString("cache-secs", "3")
                MPVLib.setPropertyString("demuxer-readahead-secs", "3")
                MPVLib.setPropertyString("demuxer-max-bytes", "16MiB")
            } else {
                MPVLib.setPropertyString("cache-secs", "30")
                MPVLib.setPropertyString("demuxer-readahead-secs", "20")
                MPVLib.setPropertyString("demuxer-max-bytes", "150MiB")
            }
        } catch (_: Throwable) {}
        if (surfaceView.holder.surface?.isValid == true) {
            loadInternal(url, startAtMs, subUrl)
        } else {
            pendingUrl = url
            pendingStartAtMs = startAtMs
            pendingSubUrl = subUrl
        }
    }

    private fun loadInternal(url: String, startAtMs: Long, subUrl: String) {
        try {
            if (startAtMs > 5_000L) {
                MPVLib.setPropertyString("start", "%.3f".format(startAtMs / 1000.0))
            } else {
                MPVLib.setPropertyString("start", "0")
            }
            MPVLib.command(arrayOf("loadfile", url, "replace"))
            if (subUrl.isNotBlank()) {
                MPVLib.command(arrayOf("sub-add", subUrl, "select"))
            }
        } catch (t: Throwable) {
            Log.w(TAG, "loadfile failed", t)
            listener.onMpvError()
        }
    }

    fun addSubtitleSlave(url: String) {
        if (url.isBlank()) return
        try { MPVLib.command(arrayOf("sub-add", url, "select")) }
        catch (t: Throwable) { Log.w(TAG, "sub-add failed", t) }
    }

    fun play()  { try { MPVLib.setPropertyBoolean("pause", false) } catch (_: Throwable) {} }
    fun pause() { try { MPVLib.setPropertyBoolean("pause", true)  } catch (_: Throwable) {} }
    fun isPlaying(): Boolean = try {
        MPVLib.getPropertyBoolean("pause") == false
    } catch (_: Throwable) { false }
    fun positionMs(): Long = try {
        ((MPVLib.getPropertyDouble("time-pos") ?: 0.0) * 1000).toLong().coerceAtLeast(0L)
    } catch (_: Throwable) { 0L }
    fun durationMs(): Long = try {
        ((MPVLib.getPropertyDouble("duration") ?: 0.0) * 1000).toLong().coerceAtLeast(0L)
    } catch (_: Throwable) { 0L }
    fun seekTo(ms: Long) {
        try {
            MPVLib.command(arrayOf("seek", "%.3f".format(ms / 1000.0), "absolute"))
        } catch (_: Throwable) {}
    }
    fun setVolume(pct: Int) {
        try { MPVLib.setPropertyInt("volume", pct.coerceIn(0, 100)) } catch (_: Throwable) {}
    }

    /* ─── Track pickers ─── */

    /** Return list of (mpv-track-id, human-label) pairs. */
    fun audioTrackList(): List<Pair<Int, String>> = trackList("audio")
    fun spuTrackList(): List<Pair<Int, String>> = trackList("sub")
    fun currentAudioTrack(): Int = currentTrack("aid")
    fun currentSpuTrack(): Int = currentTrack("sid")
    fun selectAudioTrack(id: Int) { setTrack("aid", id) }
    fun selectSpuTrack(id: Int) { setTrack("sid", id) }
    fun disableSubtitles() { setTrack("sid", -1) }

    private fun trackList(type: String): List<Pair<Int, String>> {
        val out = mutableListOf<Pair<Int, String>>()
        try {
            val count = MPVLib.getPropertyInt("track-list/count") ?: return emptyList()
            for (i in 0 until count) {
                val t = MPVLib.getPropertyString("track-list/$i/type") ?: continue
                if (t != type) continue
                val id = MPVLib.getPropertyInt("track-list/$i/id") ?: continue
                val title = MPVLib.getPropertyString("track-list/$i/title")
                val lang  = MPVLib.getPropertyString("track-list/$i/lang")
                val label = when {
                    !title.isNullOrBlank() && !lang.isNullOrBlank() -> "$title ($lang)"
                    !title.isNullOrBlank() -> title
                    !lang.isNullOrBlank() -> lang
                    else -> "Track $id"
                }
                out.add(id to label)
            }
        } catch (_: Throwable) {}
        return out
    }

    private fun currentTrack(prop: String): Int = try {
        MPVLib.getPropertyInt(prop) ?: -1
    } catch (_: Throwable) { -1 }

    private fun setTrack(prop: String, id: Int) {
        try {
            if (id < 0) MPVLib.setPropertyString(prop, "no")
            else MPVLib.setPropertyInt(prop, id)
        } catch (_: Throwable) {}
    }

    fun stop() {
        try { MPVLib.command(arrayOf("stop")) } catch (_: Throwable) {}
    }

    fun release() {
        if (released) return
        released = true
        handler.removeCallbacksAndMessages(null)
        try { surfaceView.holder.removeCallback(surfaceCallback) } catch (_: Throwable) {}
        try {
            if (surfaceView.holder.surface?.isValid == true) MPVLib.detachSurface()
        } catch (_: Throwable) {}
        try { MPVLib.removeObserver(mpvObserver) } catch (_: Throwable) {}
        try { if (initialised) MPVLib.destroy() } catch (_: Throwable) {}
        try { (surfaceView.parent as? ViewGroup)?.removeView(surfaceView) } catch (_: Throwable) {}
    }
}
