/**
 * Netflix-style image avatars.
 *
 * Each avatar is a deterministic illustrated character portrait
 * generated by DiceBear (MIT-licensed, free, no API key required —
 * https://www.dicebear.com).  We ship eleven categories spanning
 * Anime, Realistic People, Cartoon Faces, Sci-Fi Robots, Pixel
 * Art, etc.  The PNG endpoint is used (over SVG) so the older
 * Chrome 52 WebView on HK1 boxes renders the tiles reliably.
 *
 * Each tile fills its container edge-to-edge — perfect for the
 * "fills the whole screen" feel the user requested.  The previous
 * emoji-on-gradient system is gone; legacy profiles whose avatar
 * id doesn't match a current entry fall back to the first avatar
 * via `getAvatar`.
 */

/* DiceBear PNG endpoint builder.  Pin to v9.x and request a
   reasonably high resolution (256) so the tile stays sharp even
   when the picker renders the avatar at ~160 px.  All character
   portraits use radius=50 so the SVG/PNG is pre-cropped to a
   circle — eliminates a layer of CSS work on the WebView. */
const DICEBEAR = 'https://api.dicebear.com/9.x';
const dbear = (style, seed, opts = {}) => {
    const qs = new URLSearchParams({
        seed: String(seed),
        size: '256',
        radius: '50',
        backgroundType: 'gradientLinear',
        ...opts,
    }).toString();
    return `${DICEBEAR}/${style}/png?${qs}`;
};

/* Eleven Netflix-y categories.  Order = D-pad row order:
   Anime first because it's the user's lead example. */
const CATS = [
    {
        id: 'anime',
        label: 'Anime',
        style: 'lorelei',
        glow: '#FF6BCB',
        seeds: ['Yuki', 'Aiko', 'Hiroshi', 'Sakura', 'Kenji', 'Mio',
                'Ren', 'Sora', 'Akira', 'Hana', 'Riko', 'Takeshi'],
    },
    {
        id: 'realistic',
        label: 'Realistic',
        style: 'personas',
        glow: '#5DC8FF',
        seeds: ['Alex', 'Sam', 'Morgan', 'Jordan', 'Casey', 'Riley',
                'Avery', 'Quinn', 'Cameron', 'Skylar', 'Dakota', 'Reese'],
    },
    {
        id: 'cartoon',
        label: 'Cartoon',
        style: 'avataaars',
        glow: '#FACC15',
        seeds: ['Liam', 'Noah', 'Emma', 'Ava', 'Sophia', 'Mia',
                'Oliver', 'Ella', 'Mason', 'Zoe', 'Lucas', 'Aria'],
    },
    {
        id: 'peeps',
        label: 'Open Peeps',
        style: 'open-peeps',
        glow: '#FB923C',
        seeds: ['Indigo', 'Felix', 'Ivy', 'Leo', 'Theo', 'Nova',
                'Atlas', 'Wren', 'Rowan', 'Phoenix', 'Sage', 'Juno'],
    },
    {
        id: 'adventurer',
        label: 'Adventurer',
        style: 'adventurer',
        glow: '#10B981',
        seeds: ['Arthur', 'Lara', 'Drake', 'Mei', 'Roar', 'Zara',
                'Kai', 'Astra', 'Nyx', 'Bolt', 'Jade', 'Echo'],
    },
    {
        id: 'micah',
        label: 'Studio Flat',
        style: 'micah',
        glow: '#A78BFA',
        seeds: ['Vibe', 'Mood', 'Chill', 'Wave', 'Glow', 'Mint',
                'Plum', 'Coral', 'Lemon', 'Sky', 'Aqua', 'Sand'],
    },
    {
        id: 'smile',
        label: 'Big Smile',
        style: 'big-smile',
        glow: '#F472B6',
        seeds: ['Sunny', 'Joy', 'Pip', 'Buzz', 'Cherry', 'Daisy',
                'Pixie', 'Sparkle', 'Tiger', 'Star', 'Hope', 'Honey'],
    },
    {
        id: 'bottts',
        label: 'Robots',
        style: 'bottts',
        glow: '#06B6D4',
        seeds: ['R2', 'T800', 'BB8', 'WallE', 'Eve', 'K9',
                'Bender', 'Optimus', 'Beep', 'Boop', 'Zorp', 'Cog'],
    },
    {
        id: 'pixel',
        label: 'Pixel Art',
        style: 'pixel-art',
        glow: '#22D3EE',
        seeds: ['Mario', 'Link', 'Sonic', 'PacMan', 'Kirby', 'Cloud',
                'Tifa', 'Crash', 'Spyro', 'Megaman', 'Lara', 'Cid'],
    },
    {
        id: 'notion',
        label: 'Notionists',
        style: 'notionists',
        glow: '#7DD3FC',
        seeds: ['Pro', 'Coder', 'Chef', 'Pilot', 'Author', 'Dancer',
                'Painter', 'Musician', 'Detective', 'Hero', 'Sage', 'Wanderer'],
    },
    {
        id: 'fun',
        label: 'Fun Faces',
        style: 'fun-emoji',
        glow: '#FBBF24',
        seeds: ['Wow', 'Yay', 'Ha', 'Hi', 'Bye', 'Yum',
                'Cool', 'Boom', 'Wink', 'Smirk', 'Cute', 'Wild'],
    },
];

/* Expand seeds into avatar records.  ID schema: `<catId>-<idx>`. */
export const AVATAR_CATEGORIES = CATS.map((c) => ({
    id: c.id,
    label: c.label,
    items: c.seeds.map((s, i) => ({
        id: `${c.id}-${i + 1}`,
        src: dbear(c.style, s),
        glow: c.glow,
        seed: s,
        style: c.style,
    })),
}));

/* Flat list — used by `getAvatar(id)` and anywhere else the
   picker needs every avatar regardless of category. */
export const AVATARS = AVATAR_CATEGORIES.flatMap((c) => c.items);

/* Synthetic Kids profile avatar — friendly bear-ish smile that's
   NOT exposed in the picker (hidden=true, filtered out by
   ProfileEdit.jsx's visibleAvatars). */
const KIDS = {
    id: 'kids-default',
    src: dbear('big-smile', 'KidBear', { backgroundColor: 'ffd700,ff9a3c' }),
    glow: '#FFC857',
    seed: 'KidBear',
    style: 'big-smile',
    hidden: true,
};
AVATARS.push(KIDS);

export function getAvatar(id) {
    return AVATARS.find((a) => a.id === id) || AVATARS[0];
}

/**
 * Reusable circular avatar.  Renders a full-bleed PNG inside a
 * round container with a subtle glow that matches the avatar's
 * dominant color.  When `ring` is true (currently-selected
 * profile) we wrap the circle in a brand-blue focus ring.
 */
export function AvatarCircle({ avatarId, size = 96, ring = false }) {
    const a = getAvatar(avatarId);
    return (
        <span
            data-testid={`avatar-${avatarId}`}
            style={{
                display: 'inline-flex',
                position: 'relative',
                width: size,
                height: size,
                borderRadius: '50%',
                overflow: 'hidden',
                // Soft tinted plate behind the PNG so the SVG
                // background doesn't read as a flat square if
                // DiceBear ever returns a transparent corner.
                background: `radial-gradient(circle at 30% 30%, ${a.glow}33, rgba(0,0,0,0.6))`,
                boxShadow: ring
                    ? `0 0 0 3px var(--vesper-blue-bright), 0 0 32px 4px ${a.glow}66`
                    : `0 14px 36px -10px ${a.glow}88`,
                userSelect: 'none',
            }}
        >
            <img
                src={a.src}
                alt=""
                loading="lazy"
                decoding="async"
                draggable={false}
                style={{
                    position: 'absolute',
                    inset: 0,
                    width: '100%',
                    height: '100%',
                    objectFit: 'cover',
                    display: 'block',
                    pointerEvents: 'none',
                }}
                onError={(e) => {
                    // If DiceBear is unreachable, fall back to a
                    // tinted initial so the tile stays visually
                    // intact rather than collapsing to a broken
                    // image icon.
                    const el = e.currentTarget;
                    el.style.visibility = 'hidden';
                }}
            />
        </span>
    );
}
