/**
 * Studios + Box Sets — GENERATED from backend/collections_api.py
 * (COLLECTIONS dict).  Order = rail / grid order.  Artwork (logo +
 * backdrop + logo treatment) comes from `/api/collections/logos`.
 */
export const COLLECTIONS = [
    { slug: "marvel", name: "Marvel", group: "studio", moviesOnly: false, accent: "#e23636" },
    { slug: "dc", name: "DC", group: "studio", moviesOnly: false, accent: "#0476f2" },
    { slug: "disney", name: "Disney", group: "studio", moviesOnly: false, accent: "#1a6ef5" },
    { slug: "pixar", name: "Pixar", group: "studio", moviesOnly: false, accent: "#2bd1ff" },
    { slug: "star-wars", name: "Star Wars", group: "boxset", moviesOnly: false, accent: "#ffe81f" },
    { slug: "wizarding-world", name: "Wizarding World", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "middle-earth", name: "Middle-earth", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "james-bond", name: "James Bond", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "fast-furious", name: "Fast & Furious", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "jurassic", name: "Jurassic", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "mission-impossible", name: "Mission: Impossible", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "john-wick", name: "John Wick", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "spider-man", name: "Spider-Man", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "batman", name: "Batman", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "avengers", name: "Avengers", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "x-men", name: "X-Men", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "deadpool", name: "Deadpool", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "transformers", name: "Transformers", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "indiana-jones", name: "Indiana Jones", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "pirates", name: "Pirates of the Caribbean", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "toy-story", name: "Toy Story", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "shrek", name: "Shrek", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "despicable-me", name: "Despicable Me", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "matrix", name: "The Matrix", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "rocky", name: "Rocky & Creed", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "alien", name: "Alien", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "terminator", name: "Terminator", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "hunger-games", name: "The Hunger Games", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "twilight", name: "Twilight", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "godzilla", name: "MonsterVerse", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "star-trek", name: "Star Trek", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "mad-max", name: "Mad Max", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "back-to-the-future", name: "Back to the Future", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "bourne", name: "Bourne", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "die-hard", name: "Die Hard", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "oceans", name: "Ocean's", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "conjuring", name: "The Conjuring", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "scream", name: "Scream", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "planet-of-the-apes", name: "Planet of the Apes", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "ice-age", name: "Ice Age", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "kung-fu-panda", name: "Kung Fu Panda", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "httyd", name: "How to Train Your Dragon", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "dreamworks", name: "DreamWorks", group: "studio", moviesOnly: false, accent: "#ffb400" },
    { slug: "illumination", name: "Illumination", group: "studio", moviesOnly: false, accent: "#7c5cff" },
    { slug: "ghibli", name: "Studio Ghibli", group: "studio", moviesOnly: false, accent: "#ff7a1a" },
    { slug: "warner-bros", name: "Warner Bros.", group: "studio", moviesOnly: false, accent: "#3ddc84" },
    { slug: "universal", name: "Universal", group: "studio", moviesOnly: false, accent: "#f5c518" },
    { slug: "paramount", name: "Paramount", group: "studio", moviesOnly: false, accent: "#00a8e1" },
    { slug: "20th-century", name: "20th Century", group: "studio", moviesOnly: false, accent: "#e23636" },
    { slug: "a24", name: "A24", group: "studio", moviesOnly: false, accent: "#0476f2" },
    { slug: "blumhouse", name: "Blumhouse", group: "studio", moviesOnly: false, accent: "#1a6ef5" },
    { slug: "legendary", name: "Legendary", group: "studio", moviesOnly: false, accent: "#2bd1ff" },
    { slug: "lionsgate", name: "Lionsgate", group: "studio", moviesOnly: false, accent: "#ffb400" },
    { slug: "lucasfilm", name: "Lucasfilm", group: "studio", moviesOnly: false, accent: "#7c5cff" },
    { slug: "sony-pictures", name: "Sony Pictures", group: "studio", moviesOnly: false, accent: "#ff7a1a" },
    { slug: "columbia", name: "Columbia Pictures", group: "studio", moviesOnly: false, accent: "#3ddc84" },
    { slug: "mgm", name: "MGM", group: "studio", moviesOnly: false, accent: "#f5c518" },
    { slug: "new-line", name: "New Line Cinema", group: "studio", moviesOnly: false, accent: "#00a8e1" },
    { slug: "amblin", name: "Amblin", group: "studio", moviesOnly: false, accent: "#e23636" },
    { slug: "focus-features", name: "Focus Features", group: "studio", moviesOnly: false, accent: "#0476f2" },
    { slug: "searchlight", name: "Searchlight", group: "studio", moviesOnly: false, accent: "#1a6ef5" },
    { slug: "miramax", name: "Miramax", group: "studio", moviesOnly: false, accent: "#2bd1ff" },
    { slug: "aardman", name: "Aardman", group: "studio", moviesOnly: false, accent: "#ffb400" },
    { slug: "laika", name: "LAIKA", group: "studio", moviesOnly: false, accent: "#7c5cff" },
    { slug: "disney-animation", name: "Walt Disney Animation", group: "studio", moviesOnly: false, accent: "#ff7a1a" },
    { slug: "sony-animation", name: "Sony Pictures Animation", group: "studio", moviesOnly: false, accent: "#3ddc84" },
    { slug: "bad-robot", name: "Bad Robot", group: "studio", moviesOnly: false, accent: "#f5c518" },
    { slug: "working-title", name: "Working Title", group: "studio", moviesOnly: false, accent: "#00a8e1" },
    { slug: "village-roadshow", name: "Village Roadshow", group: "studio", moviesOnly: false, accent: "#e23636" },
    { slug: "touchstone", name: "Touchstone", group: "studio", moviesOnly: false, accent: "#0476f2" },
    { slug: "hbo", name: "HBO", group: "studio", moviesOnly: false, accent: "#1a6ef5" },
    { slug: "netflix-studios", name: "Netflix", group: "studio", moviesOnly: false, accent: "#2bd1ff" },
    { slug: "amazon-studios", name: "Amazon Studios", group: "studio", moviesOnly: false, accent: "#ffb400" },
    { slug: "apple-studios", name: "Apple Studios", group: "studio", moviesOnly: false, accent: "#7c5cff" },
    { slug: "studiocanal", name: "StudioCanal", group: "studio", moviesOnly: false, accent: "#ff7a1a" },
    { slug: "gaumont", name: "Gaumont", group: "studio", moviesOnly: false, accent: "#3ddc84" },
    { slug: "toho", name: "TOHO", group: "studio", moviesOnly: false, accent: "#f5c518" },
    { slug: "bbc-film", name: "BBC Film", group: "studio", moviesOnly: false, accent: "#00a8e1" },
    { slug: "neon", name: "NEON", group: "studio", moviesOnly: false, accent: "#e23636" },
    { slug: "plan-b", name: "Plan B", group: "studio", moviesOnly: false, accent: "#0476f2" },
    { slug: "skydance", name: "Skydance", group: "studio", moviesOnly: false, accent: "#1a6ef5" },
    { slug: "syncopy", name: "Syncopy", group: "studio", moviesOnly: false, accent: "#2bd1ff" },
    { slug: "bruckheimer", name: "Jerry Bruckheimer Films", group: "studio", moviesOnly: false, accent: "#ffb400" },
    { slug: "apatow", name: "Apatow Productions", group: "studio", moviesOnly: false, accent: "#7c5cff" },
    { slug: "ghost-house", name: "Ghost House Pictures", group: "studio", moviesOnly: false, accent: "#ff7a1a" },
    { slug: "iron-man", name: "Iron Man", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "thor", name: "Thor", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "captain-america", name: "Captain America", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "guardians", name: "Guardians of the Galaxy", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "ant-man", name: "Ant-Man", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "doctor-strange", name: "Doctor Strange", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "wolverine", name: "The Wolverine", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "venom", name: "Venom", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "fantastic-four", name: "Fantastic Four", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "superman", name: "Superman", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "wonder-woman", name: "Wonder Woman", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "avatar", name: "Avatar", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "dune", name: "Dune", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "blade-runner", name: "Blade Runner", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "men-in-black", name: "Men in Black", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "ghostbusters", name: "Ghostbusters", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "predator", name: "Predator", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "riddick", name: "Riddick", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "pacific-rim", name: "Pacific Rim", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "jumanji", name: "Jumanji", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "sonic", name: "Sonic the Hedgehog", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "kingsman", name: "Kingsman", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "sherlock-holmes", name: "Sherlock Holmes", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "jack-reacher", name: "Jack Reacher", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "expendables", name: "The Expendables", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "rambo", name: "Rambo", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "lethal-weapon", name: "Lethal Weapon", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "bad-boys", name: "Bad Boys", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "rush-hour", name: "Rush Hour", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "beverly-hills-cop", name: "Beverly Hills Cop", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "national-treasure", name: "National Treasure", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "the-mummy", name: "The Mummy", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "robert-langdon", name: "The Da Vinci Code", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "kill-bill", name: "Kill Bill", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "godfather", name: "The Godfather", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "karate-kid", name: "The Karate Kid", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "blade", name: "Blade", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "underworld", name: "Underworld", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "resident-evil", name: "Resident Evil", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "divergent", name: "Divergent", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "maze-runner", name: "The Maze Runner", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "narnia", name: "The Chronicles of Narnia", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "fifty-shades", name: "Fifty Shades", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "saw", name: "Saw", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "halloween", name: "Halloween", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "friday-13th", name: "Friday the 13th", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "elm-street", name: "A Nightmare on Elm Street", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "chucky", name: "Child's Play", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "evil-dead", name: "Evil Dead", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "hellraiser", name: "Hellraiser", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "final-destination", name: "Final Destination", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "paranormal-activity", name: "Paranormal Activity", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "insidious", name: "Insidious", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "the-purge", name: "The Purge", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "scary-movie", name: "Scary Movie", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "hangover", name: "The Hangover", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "american-pie", name: "American Pie", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "meet-the-parents", name: "Meet the Parents", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "austin-powers", name: "Austin Powers", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "ace-ventura", name: "Ace Ventura", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "home-alone", name: "Home Alone", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "night-at-the-museum", name: "Night at the Museum", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
    { slug: "cars", name: "Cars", group: "boxset", moviesOnly: true, accent: "#ffb100" },
    { slug: "frozen", name: "Frozen", group: "boxset", moviesOnly: true, accent: "#ff5e3a" },
    { slug: "incredibles", name: "The Incredibles", group: "boxset", moviesOnly: true, accent: "#9b5cff" },
    { slug: "finding-nemo", name: "Finding Nemo", group: "boxset", moviesOnly: true, accent: "#4cc9f0" },
    { slug: "monsters-inc", name: "Monsters, Inc.", group: "boxset", moviesOnly: true, accent: "#f72585" },
    { slug: "wreck-it-ralph", name: "Wreck-It Ralph", group: "boxset", moviesOnly: true, accent: "#06d6a0" },
    { slug: "madagascar", name: "Madagascar", group: "boxset", moviesOnly: true, accent: "#ffd166" },
    { slug: "hotel-transylvania", name: "Hotel Transylvania", group: "boxset", moviesOnly: true, accent: "#8ecae6" },
    { slug: "secret-life-of-pets", name: "The Secret Life of Pets", group: "boxset", moviesOnly: true, accent: "#ffe81f" },
    { slug: "lego-movie", name: "The LEGO Movie", group: "boxset", moviesOnly: true, accent: "#c9a24b" },
    { slug: "scooby-doo", name: "Scooby-Doo", group: "boxset", moviesOnly: true, accent: "#d4af37" },
    { slug: "rio", name: "Rio", group: "boxset", moviesOnly: true, accent: "#ff3b3b" },
];

export const STUDIOS = COLLECTIONS.filter((c) => c.group === 'studio');
export const BOX_SETS = COLLECTIONS.filter((c) => c.group === 'boxset');

export function findCollection(slug) {
    return COLLECTIONS.find((c) => c.slug === slug) || null;
}
