/**
 * Collections rail — studios + franchises.  Order here is the rail
 * order; artwork (logo + backdrop) comes from `/api/collections/logos`.
 * `moviesOnly` hides the TV tab on the collection page.
 */
export const COLLECTIONS = [
    { slug: 'marvel', name: 'Marvel', accent: '#ec1d24' },
    { slug: 'dc', name: 'DC', accent: '#0476f2' },
    { slug: 'disney', name: 'Disney', accent: '#1e5eff' },
    { slug: 'pixar', name: 'Pixar', accent: '#9ec5ff' },
    { slug: 'star-wars', name: 'Star Wars', accent: '#ffe81f' },
    { slug: 'wizarding-world', name: 'Wizarding World', accent: '#d4af37', moviesOnly: true },
    { slug: 'middle-earth', name: 'Middle-earth', accent: '#c9a84c', moviesOnly: true },
    { slug: 'james-bond', name: 'James Bond', accent: '#d9d9d9', moviesOnly: true },
    { slug: 'fast-furious', name: 'Fast & Furious', accent: '#ff7a00', moviesOnly: true },
    { slug: 'jurassic', name: 'Jurassic', accent: '#e0b400', moviesOnly: true },
    { slug: 'mission-impossible', name: 'Mission: Impossible', accent: '#ff3b30', moviesOnly: true },
    { slug: 'john-wick', name: 'John Wick', accent: '#6f8cff', moviesOnly: true },
    { slug: 'spider-man', name: 'Spider-Man', accent: '#e23636', moviesOnly: true },
    { slug: 'batman', name: 'Batman', accent: '#ffd400', moviesOnly: true },
    { slug: 'avengers', name: 'Avengers', accent: '#5aa9ff', moviesOnly: true },
    { slug: 'x-men', name: 'X-Men', accent: '#ffcc00', moviesOnly: true },
    { slug: 'deadpool', name: 'Deadpool', accent: '#ff1e3c', moviesOnly: true },
    { slug: 'transformers', name: 'Transformers', accent: '#8fd3ff', moviesOnly: true },
    { slug: 'indiana-jones', name: 'Indiana Jones', accent: '#e2a12c', moviesOnly: true },
    { slug: 'pirates', name: 'Pirates of the Caribbean', accent: '#c9b27c', moviesOnly: true },
    { slug: 'toy-story', name: 'Toy Story', accent: '#ffd23f', moviesOnly: true },
    { slug: 'shrek', name: 'Shrek', accent: '#8fd14f', moviesOnly: true },
    { slug: 'despicable-me', name: 'Despicable Me', accent: '#ffd800', moviesOnly: true },
    { slug: 'matrix', name: 'The Matrix', accent: '#00ff41', moviesOnly: true },
    { slug: 'rocky', name: 'Rocky & Creed', accent: '#ffb000', moviesOnly: true },
    { slug: 'alien', name: 'Alien', accent: '#7fe3c6', moviesOnly: true },
    { slug: 'terminator', name: 'Terminator', accent: '#ff2a2a', moviesOnly: true },
    { slug: 'hunger-games', name: 'The Hunger Games', accent: '#ff9a00', moviesOnly: true },
    { slug: 'twilight', name: 'Twilight', accent: '#c56dff', moviesOnly: true },
    { slug: 'godzilla', name: 'MonsterVerse', accent: '#4fd1ff', moviesOnly: true },
    { slug: 'star-trek', name: 'Star Trek', accent: '#ffd86b', moviesOnly: true },
    { slug: 'mad-max', name: 'Mad Max', accent: '#ff8a3d', moviesOnly: true },
    { slug: 'back-to-the-future', name: 'Back to the Future', accent: '#ff6a00', moviesOnly: true },
    { slug: 'bourne', name: 'Bourne', accent: '#9fb3c8', moviesOnly: true },
    { slug: 'die-hard', name: 'Die Hard', accent: '#ffb347', moviesOnly: true },
    { slug: 'oceans', name: "Ocean's", accent: '#ffcf5c', moviesOnly: true },
    { slug: 'conjuring', name: 'The Conjuring', accent: '#b3b3b3', moviesOnly: true },
    { slug: 'scream', name: 'Scream', accent: '#ff3b3b', moviesOnly: true },
    { slug: 'planet-of-the-apes', name: 'Planet of the Apes', accent: '#c7d2fe', moviesOnly: true },
    { slug: 'ice-age', name: 'Ice Age', accent: '#9be7ff', moviesOnly: true },
    { slug: 'kung-fu-panda', name: 'Kung Fu Panda', accent: '#ff9f1c', moviesOnly: true },
    { slug: 'httyd', name: 'How to Train Your Dragon', accent: '#ff5a36', moviesOnly: true },
    { slug: 'dreamworks', name: 'DreamWorks', accent: '#7fb3ff' },
    { slug: 'illumination', name: 'Illumination', accent: '#ffe14d' },
    { slug: 'ghibli', name: 'Studio Ghibli', accent: '#8ecae6' },
    { slug: 'warner-bros', name: 'Warner Bros.', accent: '#2f7bff' },
    { slug: 'universal', name: 'Universal', accent: '#9bd0ff' },
    { slug: 'paramount', name: 'Paramount', accent: '#5aa9ff' },
    { slug: '20th-century', name: '20th Century', accent: '#ffd36b' },
    { slug: 'a24', name: 'A24', accent: '#ffffff' },
    { slug: 'blumhouse', name: 'Blumhouse', accent: '#ff4d4d' },
    { slug: 'legendary', name: 'Legendary', accent: '#c9c9c9' },
    { slug: 'lionsgate', name: 'Lionsgate', accent: '#ffb84d' },
];

export function findCollection(slug) {
    return COLLECTIONS.find((c) => c.slug === slug) || null;
}
